//! The WCAG 2.x compliance report.
//!
//! The brief requires WCAG ratios to be emitted "as a compliance report, never
//! as the design criterion", and nothing was producing one. This does.
//!
//! Read the numbers with the caveat attached: for several pairs WCAG and APCA
//! disagree, and where they do, **APCA is the one this system was designed
//! against**. The report exists because audits ask for it, not because it is
//! how the palette was tuned. A pair that clears 7:1 and reads badly in dark
//! mode is exactly the failure mode APCA was created to fix.

use noctua_core::{apca, wcag21};
use noctua_engine::Palette;

/// One row of the compliance report.
#[derive(Debug, Clone)]
pub struct Row {
    /// Theme the pair belongs to.
    pub theme: String,
    /// Light or dark.
    pub mode: &'static str,
    /// Semantic name of the foreground.
    pub foreground: String,
    /// Semantic name of the background.
    pub background: String,
    /// The WCAG 2.x contrast ratio.
    pub ratio: f64,
    /// The APCA contrast, as a magnitude.
    pub lc: f64,
    /// Whether the ratio clears 4.5:1.
    pub aa: bool,
    /// Whether the ratio clears 7:1.
    pub aaa: bool,
}

/// Builds the report over every pair the contrast gate checks.
#[must_use]
pub fn rows(palette: &Palette) -> Vec<Row> {
    crate::contrast::pairs_with_colors(palette)
        .into_iter()
        .map(|(theme, mode, foreground, background, fg, bg)| {
            let ratio = wcag21(fg, bg);
            Row {
                theme,
                mode,
                foreground,
                background,
                ratio,
                lc: apca(fg, bg).abs(),
                aa: ratio >= 4.5,
                aaa: ratio >= 7.0,
            }
        })
        .collect()
}

/// Renders the report as Markdown for `dist/reports/`.
#[must_use]
pub fn render(palette: &Palette) -> String {
    use std::fmt::Write as _;

    let mut out = String::from(
        "<!-- Generated by noctua-colors from specs/noctua.toml - do not edit.\n\
         \x20    Regenerate: cargo xtask build -->\n\n\
         # WCAG 2.x compliance report\n\n\
         Reporting only. This palette is designed against APCA, and where the two \n\
         disagree APCA is authoritative. The `Lc` column is shown beside the ratio \n\
         so the disagreements are visible rather than buried.\n\n",
    );

    let mut current = String::new();
    for row in rows(palette) {
        let heading = format!("{}/{}", row.theme, row.mode);
        if heading != current {
            writeln!(out, "\n## {heading}\n").expect("string write");
            writeln!(
                out,
                "| foreground | background | WCAG | AA | AAA | APCA Lc |"
            )
            .expect("w");
            writeln!(out, "|---|---|---:|:-:|:-:|---:|").expect("string write");
            current = heading;
        }
        writeln!(
            out,
            "| `{}` | `{}` | {:.2}:1 | {} | {} | {:.1} |",
            row.foreground,
            row.background,
            row.ratio,
            if row.aa { "yes" } else { "no" },
            if row.aaa { "yes" } else { "no" },
            row.lc
        )
        .expect("string write");
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn shipped() -> Palette {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../specs/noctua.toml");
        noctua_engine::build(&noctua_spec::load(path).expect("valid")).expect("builds")
    }

    #[test]
    fn the_report_covers_every_pair_the_gate_checks() {
        let palette = shipped();
        assert_eq!(
            rows(&palette).len(),
            crate::contrast::check(&palette).checked
        );
    }

    #[test]
    fn ratios_stay_inside_their_defined_range() {
        for row in rows(&shipped()) {
            assert!((1.0..=21.0).contains(&row.ratio), "{row:?}");
            assert!(row.aa || !row.aaa, "AAA implies AA");
        }
    }

    #[test]
    fn the_report_shows_apca_beside_wcag_so_disagreements_are_visible() {
        let markdown = render(&shipped());
        assert!(
            markdown.contains("APCA Lc"),
            "the two must be shown together"
        );
        assert!(markdown.contains("APCA is authoritative"));
        assert!(markdown.contains("do not edit"));
    }
}
