//! Plain JSON data plus generated TypeScript types.
//!
//! Two audiences with one shape.
//!
//! `palette.json` is the **complete** record — every theme, mode, gamut and
//! step, with relative chroma and gamut headroom alongside each color. It is
//! deliberately richer than the other targets, because it is what the docs
//! site reads. That is the mechanism which makes "the site cannot drift from
//! the system" true rather than aspirational: the site is a consumer of
//! `dist/`, exactly like any other project, rather than a second
//! implementation that happens to agree.
//!
//! `index.js` and `index.d.ts` are the same data as an importable module, with
//! types narrow enough that a typo in a token name is a compile error rather
//! than an `undefined` at runtime.

use noctua_engine::{Palette, ResolvedColor, ResolvedStep};
use serde_json::{Map, Value, json};

use crate::{EmittedFile, Emitter, REGENERATE, name, tokens, value};

/// The JSON and TypeScript target.
#[derive(Debug, Clone, Copy)]
pub struct JsonTs;

impl Emitter for JsonTs {
    fn id(&self) -> &'static str {
        "json-ts"
    }

    fn describe(&self) -> &'static str {
        "structured JSON plus a typed JavaScript module; also the docs site's data source"
    }

    fn emit(&self, palette: &Palette) -> Vec<EmittedFile> {
        let data = palette_json(palette);
        let mut json_text = serde_json::to_string_pretty(&data).expect("serializes");
        json_text.push('\n');

        // The axes alone, a few hundred bytes. A consumer that only needs to
        // know which palettes exist should not have to download every one of
        // them to find out.
        let mut axes_text = serde_json::to_string_pretty(&axes_json(palette)).expect("serializes");
        axes_text.push('\n');

        let mut files = vec![
            EmittedFile::new("json/palette.json", json_text.clone()),
            EmittedFile::new("json/axes.json", axes_text),
            EmittedFile::new("ts/index.js", js_module(&json_text)),
            EmittedFile::new("ts/index.d.ts", declarations(palette)),
        ];

        // One file per theme, so a page showing a single palette fetches a
        // single palette. `palette.json` holds every theme and grows with the
        // grid; at thirty-six palettes it is several megabytes, which is not a
        // thing to download in order to recolour a swatch.
        for theme in &palette.themes {
            let mut text =
                serde_json::to_string_pretty(&theme_json(palette, theme)).expect("serializes");
            text.push('\n');
            files.push(EmittedFile::new(
                format!("json/themes/{}.json", theme.name),
                text,
            ));
        }

        files
    }
}

fn color_json(color: &ResolvedColor) -> Value {
    json!({
        "gamut": color.gamut.id(),
        "hex": value::hex(color),
        "oklch": {
            "l": round(color.oklch.l, 4),
            "c": round(color.oklch.c, 4),
            "h": round(color.oklch.h, 2),
        },
        "css": value::oklch(color),
        "relativeChroma": round(color.achieved_relative_chroma, 4),
        "requestedRelativeChroma": round(color.requested_relative_chroma, 4),
        "chromaHeadroom": round(color.chroma_headroom, 4),
    })
}

fn step_json(step: &ResolvedStep) -> Value {
    json!({
        "role": step.role,
        "index": step.index,
        "renditions": step.renditions.iter().map(color_json).collect::<Vec<_>>(),
    })
}

fn palette_json(palette: &Palette) -> Value {
    let mut root = Map::new();
    root.insert(
        "$generated".into(),
        json!(format!(
            "Generated by noctua-colors from specs/noctua.toml — do not edit. \
             Regenerate: {REGENERATE}"
        )),
    );
    root.insert("prefix".into(), json!(palette.prefix));
    root.insert(
        "gamuts".into(),
        json!(palette.gamuts.iter().map(|g| g.id()).collect::<Vec<_>>()),
    );
    root.insert("roles".into(), json!(palette.roles));
    let mut ramps = Map::new();
    for (ramp, steps) in &palette.neutral_ramps {
        ramps.insert(
            ramp.clone(),
            json!(steps.iter().map(step_json).collect::<Vec<_>>()),
        );
    }
    // `grayRamp` is the untinted ramp under the name it has always had, kept so
    // a consumer reading one ramp does not have to learn a map to keep working.
    root.insert(
        "grayRamp".into(),
        json!(
            palette
                .neutral_ramp()
                .iter()
                .map(step_json)
                .collect::<Vec<_>>()
        ),
    );
    root.insert("grayRamps".into(), Value::Object(ramps));

    // The two axes a palette sits on, so a consumer can offer them as two
    // controls rather than splitting theme names on a hyphen and guessing.
    root.insert("axes".into(), axes_json(palette));

    let mut themes = Map::new();
    for theme in &palette.themes {
        themes.insert(theme.name.clone(), theme_json(palette, theme));
    }
    root.insert("themes".into(), Value::Object(themes));

    Value::Object(root)
}

/// One theme's modes, families and semantic map.
///
/// Split out because it is emitted twice: inside `palette.json` for consumers
/// that want everything, and alone in `json/themes/<name>.json` for the
/// documentation site, which shows one palette at a time and would otherwise
/// have to download every one of them to switch.
fn theme_json(palette: &Palette, theme: &noctua_engine::ResolvedTheme) -> Value {
    let mut modes = Map::new();
    for mode in &theme.modes {
        let mut families = Map::new();
        for (family, resolved) in &mode.families {
            families.insert(
                family.clone(),
                json!({
                    "baseHue": round(resolved.base_hue, 2),
                    "steps": resolved.steps.iter().map(step_json).collect::<Vec<_>>(),
                }),
            );
        }

        // Two different maps, and the difference matters to a consumer.
        //
        // `semantic` is every emitted token to the palette step it points at —
        // `on-rejected` to `danger-bg-app`. `slots` is the contract one level
        // up: each *context* to the family that fills it. The token map cannot
        // be reduced to the slot map, because a slot contributes five tokens
        // whose names are not the slot's, and a picker that wants to offer
        // "the contexts" needs the latter.
        let mut semantic = Map::new();
        for alias in tokens::semantic_tokens(mode) {
            semantic.insert(alias.name.clone(), json!(alias.target));
        }

        let mut slots = Map::new();
        for (slot, family) in &mode.semantic {
            slots.insert(slot.clone(), json!(family));
        }

        // The gate's own measurements, serialized rather than recomputed. An
        // emitter that did its own colour math would publish numbers nothing
        // had checked.
        let contrast: Vec<Value> = noctua_check::contrast::measure(mode)
            .into_iter()
            .map(|row| {
                json!({
                    "fg": row.foreground,
                    "bg": row.background,
                    // Four places: `passes` is computed at full precision, so
                    // a coarser figure here could contradict it.
                    "lc": round(row.lc, 4),
                    "wcag": round(row.wcag, 2),
                    "minimum": row.minimum,
                    "severity": match row.severity {
                        noctua_check::Severity::Fail => "fail",
                        noctua_check::Severity::Warn => "warn",
                        noctua_check::Severity::Note => "note",
                    },
                    "passes": row.passes(),
                    "for": row.reason,
                })
            })
            .collect();

        let mut alpha = Map::new();
        for stop in tokens::alpha_tokens(palette, mode) {
            alpha.insert(
                stop.stem(),
                json!({
                    "of": stop.source(&palette.alpha.role),
                    "percentage": stop.percentage,
                    "hex": crate::value::hex_rgba(stop.step.primary(), stop.percentage),
                }),
            );
        }

        let mut scales = Map::new();
        for (scale, steps) in &mode.scales {
            scales.insert(
                scale.clone(),
                json!(steps.iter().map(step_json).collect::<Vec<_>>()),
            );
        }

        modes.insert(
            mode.mode.id().to_owned(),
            json!({
                "families": Value::Object(families),
                "semantic": Value::Object(semantic),
                "slots": Value::Object(slots),
                // `chart` stays alongside `scales` for the same reason
                // `grayRamp` does: it is the one a consumer already reads.
                "chart": mode.chart().iter().map(step_json).collect::<Vec<_>>(),
                "scales": Value::Object(scales),
                // Translucent, so no contrast row can exist for these: contrast
                // is a property of two opaque colours, and a wash composites
                // differently on every backdrop.
                "alpha": Value::Object(alpha),
                // Measured, not asserted. The gate already computes exactly
                // these numbers and already fails the build on them; publishing
                // them is what lets a consumer trust a generated palette without
                // measuring thirty-six of them by eye.
                "contrast": contrast,
            }),
        );
    }
    Value::Object(modes)
}

/// The accent and saturation axes, and which theme each pair resolves to.
///
/// Only themes generated from the grid appear here; a hand-written theme has
/// no axes and is offered by name instead.
fn axes_json(palette: &Palette) -> Value {
    let mut accents: Vec<&str> = Vec::new();
    let mut saturations: Vec<&str> = Vec::new();
    let mut grid = Map::new();

    for theme in &palette.themes {
        let (Some(accent), Some(saturation)) = (&theme.accent, &theme.saturation) else {
            continue;
        };
        if !accents.contains(&accent.as_str()) {
            accents.push(accent);
        }
        if !saturations.contains(&saturation.as_str()) {
            saturations.push(saturation);
        }
        grid.insert(format!("{accent}/{saturation}"), json!(theme.name));
    }

    json!({
        // The same hash `MANIFEST.json` carries. A consumer that pins the axes
        // downloads a few hundred bytes rather than the whole manifest, and this
        // is what lets it notice that the palette behind those axes moved.
        "specHash": palette.spec_hash,
        "accents": accents,
        "saturations": saturations,
        "themes": Value::Object(grid),
    })
}

fn js_module(json_text: &str) -> String {
    format!(
        "// Generated by noctua-colors from specs/noctua.toml — do not edit.\n\
         // Regenerate: {REGENERATE}\n\
         //\n\
         // Edits to this file will be overwritten. Change the spec instead.\n\
         \n\
         /** @type {{import('./index.d.ts').Palette}} */\n\
         export const palette = {json_text};\n\
         \n\
         export default palette;\n"
    )
}

/// The static half of the type declarations.
///
/// Split from [`declarations`] only for length: this part does not depend on
/// the palette at all.
fn interfaces() -> &'static str {
    "export interface Oklch {\n\
    \x20 /** Perceptual lightness, 0 to 1. */\n\
    \x20 l: number;\n\
    \x20 /** Chroma. */\n\
    \x20 c: number;\n\
    \x20 /** Hue in degrees. */\n\
    \x20 h: number;\n\
     }\n\
     \n\
     export interface Color {\n\
    \x20 /** The gamut this rendition resolved against. */\n\
    \x20 gamut: string;\n\
    \x20 /** Channel values as `#rrggbb`, in that gamut's encoding. */\n\
    \x20 hex: string;\n\
    \x20 oklch: Oklch;\n\
    \x20 /** Ready to drop into CSS. */\n\
    \x20 css: string;\n\
    \x20 /** Fraction of the gamut boundary actually reached. */\n\
    \x20 relativeChroma: number;\n\
    \x20 /** Fraction the spec asked for, before the gamut had a say. */\n\
    \x20 requestedRelativeChroma: number;\n\
    \x20 /** Chroma remaining between this color and the boundary. */\n\
    \x20 chromaHeadroom: number;\n\
     }\n\
     \n\
     export interface Step {\n\
    \x20 role: string;\n\
    \x20 index: number;\n\
    \x20 /** One entry per gamut, primary first. */\n\
    \x20 renditions: Color[];\n\
     }\n\
     \n\
     export interface Family {\n\
    \x20 baseHue: number;\n\
    \x20 steps: Step[];\n\
     }\n\
     \n\
     export interface ModePalette {\n\
    \x20 families: Record<FamilyName, Family>;\n\
    \x20 /** Semantic name to the `family-role` stem it points at. */\n\
    \x20 semantic: Record<SemanticName, string>;\n\
    \x20 chart: Step[];\n\
     }\n\
     \n\
     export interface Palette {\n\
    \x20 prefix: string;\n\
    \x20 gamuts: string[];\n\
    \x20 roles: RoleName[];\n\
    \x20 /** The dense neutral ramp, shared by every theme and mode. */\n\
    \x20 grayRamp: Step[];\n\
    \x20 themes: Record<ThemeName, Record<Mode, ModePalette>>;\n\
     }\n\
     \n\
     export declare const palette: Palette;\n\
     export default palette;\n"
}

fn declarations(palette: &Palette) -> String {
    use std::fmt::Write as _;

    let union = |values: &[String]| -> String {
        if values.is_empty() {
            "never".to_owned()
        } else {
            values
                .iter()
                .map(|v| format!("'{}'", name::escape(v)))
                .collect::<Vec<_>>()
                .join(" | ")
        }
    };

    let mut out = format!(
        "// Generated by noctua-colors from specs/noctua.toml — do not edit.\n\
         // Regenerate: {REGENERATE}\n\
         //\n\
         // Edits to this file will be overwritten. Change the spec instead.\n\n"
    );

    let themes: Vec<String> = palette.themes.iter().map(|t| t.name.clone()).collect();
    let families: Vec<String> = palette.themes[0].modes[0]
        .families
        .keys()
        .cloned()
        .collect();
    let semantic: Vec<String> = tokens::semantic_tokens(&palette.themes[0].modes[0])
        .into_iter()
        .map(|t| t.name)
        .collect();

    writeln!(out, "/** A theme defined in the spec. */").unwrap();
    writeln!(out, "export type ThemeName = {};\n", union(&themes)).unwrap();
    writeln!(out, "/** Light or dark. */").unwrap();
    writeln!(out, "export type Mode = 'light' | 'dark';\n").unwrap();
    writeln!(out, "/** A color family. */").unwrap();
    writeln!(out, "export type FamilyName = {};\n", union(&families)).unwrap();
    writeln!(
        out,
        "/** A functional scale role. Canonical; numbers are aliases. */"
    )
    .unwrap();
    writeln!(out, "export type RoleName = {};\n", union(&palette.roles)).unwrap();
    writeln!(
        out,
        "/** The semantic contract an application codes against. */"
    )
    .unwrap();
    writeln!(out, "export type SemanticName = {};\n", union(&semantic)).unwrap();

    out.push_str(interfaces());

    out
}

fn round(value: f64, places: i32) -> f64 {
    let scale = 10f64.powi(places);
    (value * scale).round() / scale
}

#[cfg(test)]
mod tests {
    use noctua_engine::build;

    use super::*;

    fn shipped() -> Palette {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../specs/noctua.toml");
        build(&noctua_spec::load(path).expect("valid")).expect("builds")
    }

    fn file(name: &str) -> String {
        JsonTs
            .emit(&shipped())
            .into_iter()
            .find(|f| f.path == name)
            .unwrap_or_else(|| panic!("{name} should be emitted"))
            .contents
    }

    #[test]
    fn it_emits_data_a_module_and_types() {
        let palette = shipped();
        let files = JsonTs.emit(&palette);
        let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();

        // Four fixed files, then one palette file per theme so a page showing
        // one palette fetches one palette.
        assert_eq!(
            &paths[..4],
            &[
                "json/palette.json",
                "json/axes.json",
                "ts/index.js",
                "ts/index.d.ts"
            ]
        );
        assert_eq!(paths.len(), 4 + palette.themes.len());
        assert!(paths.contains(&"json/themes/ochre-balanced.json"));
    }

    #[test]
    fn the_json_is_valid_and_complete() {
        let data: Value = serde_json::from_str(&file("json/palette.json")).expect("valid JSON");
        assert_eq!(data["prefix"], "nc");
        assert!(data["gamuts"].as_array().expect("array").len() >= 2);
        assert_eq!(data["roles"].as_array().expect("array").len(), 12);
        assert_eq!(data["grayRamp"].as_array().expect("array").len(), 24);
        assert!(data["themes"]["ochre-balanced"]["light"]["families"]["accent"].is_object());
    }

    /// The docs site reads this, so it must carry more than the hex.
    #[test]
    fn every_colour_carries_the_metadata_the_docs_site_needs() {
        let data: Value = serde_json::from_str(&file("json/palette.json")).expect("valid JSON");
        let step = &data["themes"]["ochre-balanced"]["light"]["families"]["accent"]["steps"][8];
        let color = &step["renditions"][0];

        assert!(color["hex"].as_str().expect("hex").starts_with('#'));
        assert!(color["oklch"]["l"].is_number());
        assert!(color["css"].as_str().expect("css").starts_with("oklch("));
        assert!(color["relativeChroma"].is_number());
        assert!(color["chromaHeadroom"].is_number());
        assert_eq!(step["role"], "solid");
    }

    #[test]
    fn every_gamut_gets_a_rendition() {
        let palette = shipped();
        let data: Value = serde_json::from_str(&file("json/palette.json")).expect("valid JSON");
        let renditions = data["themes"]["ochre-balanced"]["light"]["families"]["accent"]["steps"]
            [0]["renditions"]
            .as_array()
            .expect("array");
        assert_eq!(renditions.len(), palette.gamuts.len());
        assert_eq!(renditions[0]["gamut"], "srgb");
        assert_eq!(renditions[1]["gamut"], "display-p3");
    }

    #[test]
    fn the_module_is_importable_and_carries_the_warning() {
        let js = file("ts/index.js");
        assert!(js.contains("export const palette ="));
        assert!(js.contains("export default palette;"));
        assert!(js.contains("do not edit"));
    }

    /// A typo in a token name should be a compile error, not an `undefined`.
    #[test]
    fn the_types_narrow_names_to_unions() {
        let dts = file("ts/index.d.ts");
        assert!(dts.contains("export type ThemeName = 'ochre-balanced' |"));

        // Every theme, read from the palette rather than pinned to whichever
        // one happens to sort last — that spelling broke the moment an accent
        // was added, and said nothing useful when it did.
        for theme in &shipped().themes {
            assert!(
                dts.contains(&format!("'{}'", theme.name)),
                "{} is missing from the union",
                theme.name
            );
        }
        assert!(dts.contains("export type Mode = 'light' | 'dark';"));
        assert!(dts.contains("'bg-app'"), "roles must be a union: {dts}");
        assert!(dts.contains("'accent'"), "semantic names must be a union");
        assert!(dts.contains("export declare const palette: Palette;"));
    }

    #[test]
    fn output_is_deterministic() {
        assert_eq!(JsonTs.emit(&shipped()), JsonTs.emit(&shipped()));
    }
}
