//! Output targets.
//!
//! Every emitter takes the same finished [`Palette`] and writes it in one
//! format. Adding a target is one file and one line in [`registry`] — never a
//! refactor.
//!
//! **This crate performs no color math.** Colors arrive resolved and
//! quantized; the job here is formatting. If an emitter ever needs to compute
//! a color, the computation belongs upstream, or the two would disagree about
//! what was checked versus what shipped.
//!
//! # Generated-file headers
//!
//! Every emitted file carries a header saying it is generated, from what, and
//! how to regenerate it. The header deliberately contains **no version string
//! and no content hash**: either would rewrite every file in `system/` whenever
//! anything changed, burying a one-token diff in hundreds of lines of churn.
//!
//! Provenance lives in [`manifest`] instead — one file that carries the tool
//! version, the spec path, and a hash per artifact.

pub mod css;
pub mod dtcg;
pub mod json_ts;
pub mod name;
pub mod output;
pub mod qml;
pub mod reports;
pub mod rust;
pub mod scss;
pub mod tailwind;
pub mod tokens;
pub mod value;

use noctua_engine::Palette;

/// One file an emitter produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmittedFile {
    /// Path relative to `system/`, using forward slashes.
    pub path: String,
    /// Complete file contents.
    pub contents: String,
}

impl EmittedFile {
    /// Builds a file.
    #[must_use]
    pub fn new(path: impl Into<String>, contents: impl Into<String>) -> Self {
        Self {
            path: path.into(),
            contents: contents.into(),
        }
    }
}

/// A format `system/` can be written in.
pub trait Emitter {
    /// Stable identifier, as named in the spec's `consumers` entries.
    fn id(&self) -> &'static str;

    /// One line describing what this target is for, shown by the CLI.
    fn describe(&self) -> &'static str;

    /// Produces every file for this target.
    ///
    /// Output must be deterministic: the same palette produces byte-identical
    /// files, every time, on every machine.
    fn emit(&self, palette: &Palette) -> Vec<EmittedFile>;
}

/// Every emitter, in a fixed order.
///
/// The order is the order `system/` is written in and the order the CLI lists
/// them; it is fixed so output never depends on iteration order.
#[must_use]
pub fn registry() -> Vec<Box<dyn Emitter>> {
    vec![
        Box::new(css::Css),
        Box::new(tailwind::Tailwind),
        Box::new(rust::Rust),
        Box::new(dtcg::Dtcg),
        Box::new(json_ts::JsonTs),
        Box::new(scss::Scss),
        Box::new(qml::Qml),
        Box::new(reports::Reports),
    ]
}

/// Looks up an emitter by its identifier.
#[must_use]
pub fn by_id(id: &str) -> Option<Box<dyn Emitter>> {
    registry().into_iter().find(|e| e.id() == id)
}

/// Every emitter identifier, for validation and help text.
#[must_use]
pub fn ids() -> Vec<&'static str> {
    registry().iter().map(|e| e.id()).collect()
}

/// Runs every emitter, returning all files sorted by path.
#[must_use]
pub fn emit_all(palette: &Palette) -> Vec<EmittedFile> {
    let mut files: Vec<EmittedFile> = registry()
        .iter()
        .flat_map(|emitter| emitter.emit(palette))
        .collect();
    files.sort_by(|a, b| a.path.cmp(&b.path));
    files
}

/// The command that regenerates everything, quoted in every header.
pub const REGENERATE: &str = "cargo xtask build";

/// Where this project lives.
///
/// Emitted into generated manifests, so it is a fact about the project rather
/// than about any one target. Registry metadata is checked against it: npm
/// rejects a provenance attestation whose `repository` does not match the
/// publishing repository **case-sensitively**, so this string and the one in
/// `package.json` have to agree exactly.
pub const REPOSITORY: &str = "https://github.com/noctua-world/noctua-colors";

/// Where the documentation site is served.
pub const HOMEPAGE: &str = "https://noctua-world.github.io/noctua-colors/";

/// The line every generated file leads with, in that file's comment syntax.
///
/// `spec` is the path the palette was compiled from.
#[must_use]
pub fn header(spec: &str, comment: CommentStyle) -> String {
    let lines = [
        "Generated by noctua-colors — do not edit.".to_owned(),
        format!("Source: {spec}"),
        format!("Regenerate: {REGENERATE}"),
        String::new(),
        "Edits to this file will be overwritten. Change the spec instead.".to_owned(),
    ];

    match comment {
        CommentStyle::Block => {
            let body: String = lines
                .iter()
                .map(|line| {
                    if line.is_empty() {
                        "   *\n".to_owned()
                    } else {
                        format!("   * {line}\n")
                    }
                })
                .collect();
            format!("/*!\n{body}   */\n")
        }
        CommentStyle::Line(marker) => lines
            .iter()
            .map(|line| {
                if line.is_empty() {
                    format!("{marker}\n")
                } else {
                    format!("{marker} {line}\n")
                }
            })
            .collect(),
    }
}

/// How a target's language spells a comment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommentStyle {
    /// A `/* ... */` block.
    Block,
    /// Repeated line comments with the given marker, such as `//` or `#`.
    Line(&'static str),
}

/// Builds `system/MANIFEST.json`.
///
/// This is where provenance lives, so that headers can stay stable. It records
/// the tool version, the spec it was built from, a hash of that spec, and a
/// hash of every emitted file — enough for a consumer to verify what it has
/// without rebuilding.
///
/// # Panics
///
/// Never in practice: the value built here is a map of strings, which
/// `serde_json` cannot fail to serialize.
#[must_use]
pub fn manifest(
    identity: &noctua_engine::Identity,
    spec_path: &str,
    spec_text: &str,
    files: &[EmittedFile],
) -> EmittedFile {
    let mut root = serde_json::Map::new();
    root.insert("tool".into(), "noctua-colors".into());
    // `version` keeps meaning the **compiler's** version, unchanged, because
    // TOKEN-POLICY.md tells consumers to diff this file: adding a key is safe
    // and repurposing one is not. `systemVersion` is the number that matters
    // to anyone installing the colours, and it is new.
    root.insert("version".into(), env!("CARGO_PKG_VERSION").into());
    root.insert("systemVersion".into(), identity.version.clone().into());
    root.insert("system".into(), identity.name.clone().into());
    root.insert("regenerate".into(), REGENERATE.into());
    root.insert("spec".into(), spec_path.into());
    root.insert("specHash".into(), hash(spec_text.as_bytes()).into());

    let mut artifacts = serde_json::Map::new();
    for file in files {
        artifacts.insert(file.path.clone(), hash(file.contents.as_bytes()).into());
    }
    root.insert("files".into(), serde_json::Value::Object(artifacts));

    let mut text = serde_json::to_string_pretty(&serde_json::Value::Object(root))
        .expect("a map of strings always serializes");
    text.push('\n');
    EmittedFile::new("MANIFEST.json", text)
}

/// A short, stable content hash.
///
/// Delegates to `noctua_spec`, so the hash in `MANIFEST.json` and the one in
/// `json/axes.json` are the same string by construction rather than by two
/// implementations happening to agree.
fn hash(bytes: &[u8]) -> String {
    noctua_spec::content_hash(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_emitter_has_a_unique_identifier() {
        let mut ids = ids();
        let count = ids.len();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), count, "emitter identifiers must be unique");
        assert_eq!(count, 8, "the seven token targets plus compliance reports");
    }

    #[test]
    fn every_emitter_can_be_looked_up_by_id() {
        for id in ids() {
            let emitter = by_id(id).unwrap_or_else(|| panic!("{id} is registered"));
            assert_eq!(emitter.id(), id);
            assert!(!emitter.describe().is_empty(), "{id} needs a description");
        }
        assert!(by_id("nonexistent").is_none());
    }

    #[test]
    fn headers_say_what_they_must() {
        for style in [
            CommentStyle::Block,
            CommentStyle::Line("//"),
            CommentStyle::Line("#"),
        ] {
            let text = header("specs/noctua.toml", style);
            assert!(text.contains("Generated by noctua-colors"), "{text}");
            assert!(text.contains("do not edit"), "{text}");
            assert!(
                text.contains("specs/noctua.toml"),
                "should name its source: {text}"
            );
            assert!(
                text.contains(REGENERATE),
                "should say how to regenerate: {text}"
            );
            assert!(text.ends_with('\n'));
        }
    }

    /// The reason headers carry no version and no hash.
    #[test]
    fn headers_are_stable_across_builds() {
        assert_eq!(
            header("specs/noctua.toml", CommentStyle::Block),
            header("specs/noctua.toml", CommentStyle::Block)
        );
        let text = header("specs/noctua.toml", CommentStyle::Block);
        assert!(
            !text.contains(env!("CARGO_PKG_VERSION")),
            "a version in the header rewrites every file on every release: {text}"
        );
    }

    fn identity() -> noctua_engine::Identity {
        noctua_engine::Identity {
            version: "9.9.9".to_owned(),
            name: "test-system".to_owned(),
            description: "a fixture".to_owned(),
        }
    }

    #[test]
    fn the_manifest_records_provenance_for_every_file() {
        let files = [
            EmittedFile::new("css/ochre-balanced.css", ":root {}"),
            EmittedFile::new("scss/_noctua.scss", "$a: 1;"),
        ];
        let manifest = manifest(
            &identity(),
            "specs/noctua.toml",
            "[families.accent]",
            &files,
        );
        assert_eq!(manifest.path, "MANIFEST.json");

        let parsed: serde_json::Value =
            serde_json::from_str(&manifest.contents).expect("valid JSON");
        assert_eq!(parsed["tool"], "noctua-colors");
        assert_eq!(parsed["spec"], "specs/noctua.toml");
        assert!(
            parsed["specHash"]
                .as_str()
                .expect("string")
                .starts_with("blake3:")
        );
        assert!(parsed["files"]["css/ochre-balanced.css"].is_string());
        assert!(parsed["files"]["scss/_noctua.scss"].is_string());
    }

    /// The two versions are both recorded, and they are not the same key.
    ///
    /// `version` has meant the compiler's since 0.1.0 and `TOKEN-POLICY.md`
    /// tells consumers to diff this file, so it keeps that meaning. The colour
    /// system's version is the new key — adding one is safe, repurposing one
    /// silently changes what an existing diff means.
    #[test]
    fn the_manifest_separates_the_two_versions() {
        let manifest = manifest(&identity(), "s.toml", "x", &[]);
        let parsed: serde_json::Value =
            serde_json::from_str(&manifest.contents).expect("valid JSON");

        assert_eq!(parsed["systemVersion"], "9.9.9", "the colour system's");
        assert_eq!(parsed["system"], "test-system");
        assert_eq!(
            parsed["version"],
            env!("CARGO_PKG_VERSION"),
            "`version` must still be the compiler's"
        );
        assert_ne!(parsed["version"], parsed["systemVersion"]);
    }

    #[test]
    fn the_manifest_changes_when_a_file_does() {
        let before = manifest(
            &identity(),
            "s.toml",
            "x",
            &[EmittedFile::new("a.css", ":root{}")],
        );
        let after = manifest(
            &identity(),
            "s.toml",
            "x",
            &[EmittedFile::new("a.css", ":root{ }")],
        );
        assert_ne!(before.contents, after.contents);
    }
}
