//! Compliance reports.
//!
//! Not tokens: numbers *about* the tokens, for the audits that ask for them.
//! Emitted as a target like any other so they cannot go stale — a report
//! regenerated by the same command as the palette it describes cannot
//! disagree with it.

use noctua_engine::Palette;

use crate::{EmittedFile, Emitter};

/// The compliance-report target.
#[derive(Debug, Clone, Copy)]
pub struct Reports;

impl Emitter for Reports {
    fn id(&self) -> &'static str {
        "reports"
    }

    fn describe(&self) -> &'static str {
        "WCAG 2.x compliance and colour-vision margin reports"
    }

    fn emit(&self, palette: &Palette) -> Vec<EmittedFile> {
        vec![
            EmittedFile::new("reports/wcag.md", noctua_check::wcag::render(palette)),
            EmittedFile::new("reports/colour-vision.md", cvd_report(palette)),
        ]
    }
}

/// How much separation every pair of semantic families keeps under each
/// deficiency.
///
/// A margin, not a verdict. The measured ceiling for a semantic set this size
/// is well under a just-noticeable difference, so the useful question is never
/// "did it pass" but "how much room is there, and where is it thinnest".
///
/// Every pair, not only the pairs the gate judges. The gate is deliberately
/// curated — it fails on confusions that change what the interface *said* —
/// and this table is where a confusion that is merely awkward stays findable.
fn cvd_report(palette: &Palette) -> String {
    use std::fmt::Write as _;

    let mut out = String::from(
        "<!-- Generated by noctua-colors from specs/noctua.toml - do not edit.\n\
         \x20    Regenerate: cargo xtask build -->\n\n\
         # Colour-vision separation report\n\n\
         Perceptual distance between semantic colors, as simulated for each \n\
         dichromacy. A just-noticeable difference is about 0.02.\n\n\
         Every pair of semantic families, not only the ones the build gates \n\
         on. The gate is curated; this is the whole surface, so a collision \n\
         that is awkward rather than dangerous stays findable.\n\n\
         These numbers are deliberately published rather than reduced to a \n\
         verdict. Ten semantic colors cannot be made mutually distinguishable \n\
         under all three dichromacies by colour alone — the palette maximises \n\
         the separation available and the remainder has to come from an icon, \n\
         a label, or shape.\n\n",
    );

    let mut current = String::new();
    for (theme, mode, pair, deficiency, apart) in noctua_check::cvd::margins(palette) {
        let heading = format!("{theme}/{mode}");
        if heading != current {
            writeln!(out, "\n## {heading}\n").expect("string write");
            writeln!(out, "| pair | deficiency | separation |").expect("string write");
            writeln!(out, "|---|---|---:|").expect("string write");
            current = heading;
        }
        writeln!(out, "| {pair} | {} | {apart:.4} |", deficiency.id()).expect("string write");
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn shipped() -> Palette {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../specs/noctua.toml");
        noctua_engine::build(&noctua_spec::load(path).expect("valid")).expect("builds")
    }

    #[test]
    fn both_reports_are_emitted_with_the_generated_warning() {
        let files = Reports.emit(&shipped());
        assert_eq!(files.len(), 2);
        for file in &files {
            assert!(file.contents.contains("do not edit"), "{}", file.path);
            assert!(file.contents.contains(crate::REGENERATE), "{}", file.path);
        }
    }

    #[test]
    fn the_wcag_report_exists_because_audits_ask_for_it() {
        let files = Reports.emit(&shipped());
        let wcag = files
            .iter()
            .find(|f| f.path == "reports/wcag.md")
            .expect("wcag");
        assert!(wcag.contents.contains("APCA is authoritative"));
        assert!(wcag.contents.contains(":1 |"), "should tabulate ratios");
    }

    #[test]
    fn the_colour_vision_report_publishes_margins_rather_than_a_verdict() {
        let files = Reports.emit(&shipped());
        let cvd = files
            .iter()
            .find(|f| f.path == "reports/colour-vision.md")
            .expect("cvd report");
        assert!(cvd.contents.contains("danger vs success"));
        assert!(cvd.contents.contains("deuteranopia"));
        assert!(
            cvd.contents.contains("icon"),
            "the report must say what to do about a thin margin"
        );
    }
}
