//! Building the playground's WebAssembly bundle.
//!
//! Two steps: compile `noctua-wasm` for `wasm32-unknown-unknown`, then run
//! `wasm-bindgen` over the result to produce the JavaScript that calls it.
//!
//! # No CLI to install
//!
//! The bindgen step runs **in process**, through `wasm-bindgen-cli-support`,
//! rather than by shelling out to a `wasm-bindgen` binary. That keeps the
//! bootstrap promise intact: a fresh clone with nothing but rustup builds the
//! whole site, playground included. A missing external tool would turn
//! `cargo xtask build` into a two-step process with a failure mode that only
//! appears on other people's machines.
//!
//! # The target is installed if missing
//!
//! `rustup target add wasm32-unknown-unknown` is idempotent and cheap, so it
//! runs rather than being demanded of the developer — and it says so when it
//! does something.
//!
//! # When wasm is unavailable
//!
//! The playground is an enhancement. If the target cannot be installed —
//! offline, or a toolchain without rustup — the build reports it and carries
//! on without a bundle. The site still renders every palette, every ramp and
//! every gate; the editor is what goes missing.

use std::path::Path;
use std::process::Command;

use crate::ui;

/// The wasm target triple.
const TARGET: &str = "wasm32-unknown-unknown";

/// Where the bundle lands, relative to the site's output directory.
pub(crate) const OUTPUT_DIR: &str = "playground";

/// Files the bundle consists of, for the site to reference and the sync check
/// to know about.
pub(crate) const OUTPUT_FILES: &[&str] = &["noctua_wasm.js", "noctua_wasm_bg.wasm"];

/// Builds the playground bundle into `site_root/playground/`.
///
/// # Errors
///
/// Only for a failure that is worth stopping the build over: a compile error
/// in the crate itself, or a bindgen failure. A missing target that cannot be
/// installed returns `Ok(false)` — the site is still worth shipping.
pub(crate) fn build(root: &Path, site_root: &Path) -> Result<bool, String> {
    if !ensure_target()? {
        ui::warn("the wasm target is unavailable; the site will ship without the playground");
        return Ok(false);
    }

    let status = Command::new(env!("CARGO"))
        .current_dir(root)
        .args([
            "build",
            "--quiet",
            "--package",
            "noctua-wasm",
            "--target",
            TARGET,
            "--release",
        ])
        .status()
        .map_err(|error| format!("could not run cargo: {error}"))?;

    if !status.success() {
        return Err("noctua-wasm did not compile for the browser".to_owned());
    }

    let artifact = root
        .join("target")
        .join(TARGET)
        .join("release")
        .join("noctua_wasm.wasm");

    let out = site_root.join(OUTPUT_DIR);
    std::fs::create_dir_all(&out)
        .map_err(|error| format!("could not create {}: {error}", out.display()))?;

    bindgen(&artifact, &out)?;
    verify_bindings(root, &out)?;

    let bytes = OUTPUT_FILES
        .iter()
        .filter_map(|name| std::fs::metadata(out.join(name)).ok())
        .map(|m| m.len())
        .sum::<u64>();
    ui::ok(&format!("playground bundle, {} KB", bytes / 1024));

    Ok(true)
}

/// Runs wasm-bindgen over the compiled artifact.
///
/// Web target, so the output is an ES module the page imports directly — no
/// bundler, matching the rest of the site.
fn bindgen(artifact: &Path, out: &Path) -> Result<(), String> {
    use wasm_bindgen_cli_support::Bindgen;

    Bindgen::new()
        .input_path(artifact)
        .web(true)
        .map_err(|error| format!("wasm-bindgen rejected the web target: {error}"))?
        .typescript(false)
        .remove_name_section(true)
        .remove_producers_section(true)
        .generate(out)
        .map_err(|error| format!("wasm-bindgen failed: {error}"))
}

/// Checks that every name the playground imports is a name the bindings
/// export.
///
/// The two files are generated by different tools and written by different
/// hands, and nothing else connects them. A renamed `#[wasm_bindgen]`
/// function produces a bundle that builds cleanly, ships cleanly, and throws
/// on load in the browser — where nobody running the build will see it. So it
/// is checked here, where the failure is a build error with both names in it.
///
/// # Errors
///
/// A name imported but not exported, or either file being unreadable.
fn verify_bindings(root: &Path, out: &Path) -> Result<(), String> {
    let script = root.join("docs-site/js/playground.js");
    let Ok(source) = std::fs::read_to_string(&script) else {
        // No playground script: nothing claims a contract, so there is none
        // to break.
        return Ok(());
    };

    let bindings = std::fs::read_to_string(out.join("noctua_wasm.js"))
        .map_err(|error| format!("could not read the generated bindings: {error}"))?;

    let missing: Vec<String> = imported_names(&source)
        .into_iter()
        .filter(|name| !exports(&bindings, name))
        .collect();

    if missing.is_empty() {
        return Ok(());
    }

    Err(format!(
        "docs-site/js/playground.js imports {} the bindings do not export: {}\n  \
         rename the `#[wasm_bindgen]` function in crates/noctua-wasm, or the import",
        if missing.len() == 1 {
            "a name"
        } else {
            "names"
        },
        missing.join(", ")
    ))
}

/// The names in the script's `import ... from` clause.
///
/// Handles the default import and `a as b` renaming, which is the whole
/// syntax this one statement uses.
fn imported_names(source: &str) -> Vec<String> {
    let Some(start) = source.find("import ") else {
        return Vec::new();
    };
    let rest = &source[start + "import ".len()..];
    let Some(end) = rest.find(" from") else {
        return Vec::new();
    };

    rest[..end]
        .replace(['{', '}', '\n'], " ")
        .split(',')
        .filter_map(|part| {
            // `default_spec as defaultSpec` is exported under the first name.
            let name = part.split_whitespace().next()?;
            (!name.is_empty()).then(|| name.to_owned())
        })
        .collect()
}

/// Whether the generated bindings export a name.
///
/// `init` is the default export, which wasm-bindgen writes as
/// `export { initSync, __wbg_init as default }` rather than as a named
/// function.
fn exports(bindings: &str, name: &str) -> bool {
    if name == "init" {
        return bindings.contains("as default");
    }
    bindings.contains(&format!("export function {name}("))
}

/// Installs the wasm target when it is missing.
///
/// # Errors
///
/// Only when rustup itself misbehaves in a way worth reporting. A rustup that
/// is simply absent returns `Ok(false)`.
fn ensure_target() -> Result<bool, String> {
    let installed = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();

    let Ok(output) = installed else {
        // No rustup. The target may still be present through another
        // toolchain, so this is not conclusive — try to build and let the
        // compiler answer.
        return Ok(true);
    };

    if String::from_utf8_lossy(&output.stdout)
        .lines()
        .any(|line| line.trim() == TARGET)
    {
        return Ok(true);
    }

    ui::detail(&format!("installing the {TARGET} target"));
    let added = Command::new("rustup")
        .args(["target", "add", TARGET])
        .status()
        .map_err(|error| format!("could not run rustup: {error}"))?;

    Ok(added.success())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The names are a contract between three places: this module, the page
    /// that imports the module, and the sync check that must not treat the
    /// bundle as drift.
    #[test]
    fn the_bundle_is_an_es_module_and_a_wasm_file() {
        let extensions: Vec<&str> = OUTPUT_FILES
            .iter()
            .filter_map(|f| Path::new(f).extension()?.to_str())
            .collect();
        assert!(extensions.contains(&"js"), "{extensions:?}");
        assert!(extensions.contains(&"wasm"), "{extensions:?}");
    }

    #[test]
    fn the_import_clause_is_read_including_renames() {
        let source = "\
import init, {
  compile,
  default_spec as defaultSpec,
} from \"../playground/noctua_wasm.js\";
";
        assert_eq!(
            imported_names(source),
            ["init", "compile", "default_spec"],
            "a renamed import is exported under its original name"
        );
    }

    #[test]
    fn the_default_export_counts_as_exported() {
        let bindings = "export function compile(s) {}\nexport { initSync, __wbg_init as default };";
        assert!(exports(bindings, "init"), "init is the default export");
        assert!(exports(bindings, "compile"));
        assert!(!exports(bindings, "renamed"));
    }
}
